<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="css/normalize.css">
        <link rel="stylesheet" href="css/style.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
        <script src="utilities/utilities.js"></script>
        <title>Travel Tips - Japon</title>
        <link rel="stylesheet" href="css/style.css">
    </head>
    <body>
        <header>
			<div class="container">
				<section>
					<a href="index.php">
						<img class="logo" src="img/logo.png" alt="Logo de Travel Tips - Japan" />
					</a>
				</section>
				<nav>
    		<a href="register.phtml">Créér un compte</a>
    		<a href="login.phtml">Connexion</a>
    		</nav>
			</div>
		</header>
		<!--MAIN CONTENT-->
		<main class="container">
			<h1>Connexion</h1>
      <form class="generic-form" action="application/login.php" method="POST">


	<fieldset>
		<legend>Informations d'authentification</legend>
		<ul>
			<li>
				<label for="email">E-mail :</label>
				<input id="email" type="text" name="email" required>
			</li>
			<li>
				<label for="password">Mot de passe :</label>
				<input id="password" type="password" name="password" required>
			</li>
		</ul>
	</fieldset>

	<ul>
		<li>
			<input class="button button-primary" type="submit" value="Connexion">
			<a class="button button-cancel small" href="index.phtml">Annuler</a>
		</li>
	</ul>
</form>
		</main>
		<!--FOOTER-->
		<footer id="copyright">
				   <img alt="Propriété de Damien Rosina" style="border-width:0" src="img/logo.png" /></a><br /><span>Ce projet est la réalisation de Damien Rosina</span>
		</footer>
    </body>
</html>
